import { NextResponse } from "next/server";
import { z } from "zod";
import { requireProfile } from "@/lib/auth/session";
import { listUsersForAdmin } from "@/lib/auth/mobile-login";
import { canManageUsersModule } from "@/lib/auth/modules";
import { isDeveloperIdentity } from "@/lib/auth/display";
import { canManageTargetRole, isExecutiveRole } from "@/lib/auth/roles";
import { ROLE_PERMISSIONS, type AppRole, type CompanyScope } from "@/types/database";
import {
  loadDeveloperProfile,
} from "@/lib/security/developer-override";
import { createCrmUser, isManageableRole } from "@/lib/security/user-admin";

export async function GET() {
  try {
    const profile = await requireProfile();
    if (
      !ROLE_PERMISSIONS[profile.role].canManageUsers ||
      !canManageUsersModule(profile)
    ) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    const viewerIsDeveloper = isDeveloperIdentity(profile);
    const users = await listUsersForAdmin({ viewerIsDeveloper });
    return NextResponse.json({ users });
  } catch {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
}

const createSchema = z.object({
  email: z.string().email().optional().or(z.literal("")),
  fullName: z.string().min(1).max(120),
  role: z.string(),
  mobile: z.string().min(8),
  pin: z.string().optional(),
  confirmPin: z.string().optional(),
  companyScope: z.enum(["KALYANI", "RADHASWAMI", "ALL"]).optional(),
  department: z.string().max(80).optional(),
  allowedModules: z.array(z.string()).optional(),
  isActive: z.boolean().optional(),
  confirm: z.boolean().optional(),
});

export async function POST(request: Request) {
  try {
    const profile = await requireProfile();
    if (
      !ROLE_PERMISSIONS[profile.role].canManageUsers ||
      !canManageUsersModule(profile) ||
      !isExecutiveRole(profile.role)
    ) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const parsed = createSchema.safeParse(await request.json());
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid request. Name, mobile, role, and PIN are required." },
        { status: 400 }
      );
    }
    const body = parsed.data;
    if (!isManageableRole(body.role)) {
      return NextResponse.json({ error: "Invalid role." }, { status: 400 });
    }

    const actor =
      (await loadDeveloperProfile(profile.id)) ||
      ({
        ...profile,
        is_developer: Boolean(profile.is_developer),
        is_primary_owner: Boolean(profile.is_primary_owner),
      } as Awaited<ReturnType<typeof loadDeveloperProfile>>);

    if (!actor) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Business CEO/Owner accounts are configurable; primary developer identity
    // is never created through this path (is_developer always false).
    const creatingOwner = body.role === "OWNER";
    const actorIsDev = isDeveloperIdentity(profile);
    const mayCreate =
      actorIsDev ||
      profile.role === "OWNER" ||
      (isExecutiveRole(profile.role) &&
        (creatingOwner
          ? ["CEO_1", "CEO_2", "CEO_3", "CEO_4"].includes(profile.role)
          : canManageTargetRole(profile.role, body.role as AppRole) ||
            ["CEO_1", "CEO_2", "CEO_3", "CEO_4", "ADMIN", "SALES_MANAGER", "SALESMAN", "ACCOUNTANT", "VIEWER"].includes(
              body.role
            )));

    if (!mayCreate) {
      return NextResponse.json(
        { error: "You are not authorised to create this role." },
        { status: 403 }
      );
    }

    if (
      creatingOwner &&
      !["OWNER", "CEO_1", "CEO_2", "CEO_3", "CEO_4"].includes(profile.role) &&
      !actorIsDev
    ) {
      return NextResponse.json(
        { error: "Only CEO/Owner can create CEO/Owner accounts." },
        { status: 403 }
      );
    }

    if (!body.confirm) {
      return NextResponse.json(
        { error: "Confirmation required.", code: "CONFIRM_REQUIRED" },
        { status: 400 }
      );
    }

    const result = await createCrmUser({
      actor,
      email: body.email || undefined,
      fullName: body.fullName,
      role: body.role as AppRole,
      mobile: body.mobile,
      pin: body.pin,
      confirmPin: body.confirmPin,
      autoGeneratePin: !body.pin,
      companyScope: body.companyScope as CompanyScope | undefined,
      department: body.department,
      allowedModules: body.allowedModules,
      isActive: body.isActive,
    });
    if (!result.ok) {
      return NextResponse.json({ error: result.error }, { status: 400 });
    }
    return NextResponse.json({
      ok: true,
      userId: result.userId,
      mobile: result.mobile,
      // Plaintext temporary PIN returned once only — never logged/stored.
      temporaryPin: result.temporaryPin,
      pinAutoGenerated: result.pinAutoGenerated === true,
    });
  } catch {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
}
