import { createServiceClient } from "@/lib/supabase/admin";
import {
  generateTemporaryPin,
  hashPin,
  isValidPin,
  normalizeMobile,
  stripPinMetadata,
} from "@/lib/auth/pin";
import {
  revokeAllDevicesAndSessions,
} from "@/lib/auth/mobile-login";
import { canResetOtherUserPin, isExecutiveRole } from "@/lib/auth/roles";
import {
  assertCanModifyPrimaryOwner,
  loadDeveloperProfile,
  requestClientInfo,
  writeDeveloperAudit,
  type DeveloperOperation,
  type DeveloperProfile,
} from "@/lib/security/developer-override";
import type { AppRole, CompanyScope, Profile } from "@/types/database";
import {
  defaultModulesForRole,
  sanitizeModules,
} from "@/lib/auth/modules";

const MANAGEABLE_ROLES: AppRole[] = [
  "OWNER",
  "CEO_1",
  "CEO_2",
  "CEO_3",
  "ADMIN",
  "SALES_MANAGER",
  "SALESMAN",
  "ACCOUNTANT",
  "VIEWER",
];

export function isManageableRole(role: string): role is AppRole {
  return (MANAGEABLE_ROLES as string[]).includes(role);
}

/** Internal Supabase email for mobile+PIN users (never shown as a login field). */
export function internalEmailFromMobile(mobile: string): string {
  return `u${mobile}@crm.internal`;
}

async function auditAdmin(
  actorId: string,
  action: string,
  targetUserId: string | null,
  metadata: Record<string, unknown> = {},
  success = true
) {
  const { ipAddress, userAgent } = await requestClientInfo();
  const admin = createServiceClient();
  await admin.from("crm_audit_logs").insert({
    user_id: actorId,
    action,
    module: "user_management",
    record_type: "crm_profiles",
    record_id: targetUserId || actorId,
    metadata: stripPinMetadata({
      ...metadata,
      success,
      target_user: targetUserId || undefined,
    }),
    ip_address: ipAddress,
    user_agent: userAgent,
  });
}

export async function createCrmUser(input: {
  actor: DeveloperProfile | Profile;
  email?: string;
  fullName: string;
  role: AppRole;
  mobile: string;
  pin?: string;
  confirmPin?: string;
  /** When mobile is set and pin is blank, auto-generate a temporary PIN. Default true. */
  autoGeneratePin?: boolean;
  companyScope?: CompanyScope;
  department?: string;
  allowedModules?: string[] | null;
  isActive?: boolean;
  temporaryPassword?: string;
}): Promise<
  | {
      ok: true;
      userId: string;
      temporaryPin?: string;
      pinAutoGenerated?: boolean;
      mobile: string;
    }
  | { ok: false; error: string }
> {
  if (!input.fullName.trim()) {
    return { ok: false, error: "Full name is required." };
  }
  if (!isManageableRole(input.role)) {
    return { ok: false, error: "Invalid role." };
  }
  if (!isExecutiveRole(input.actor.role)) {
    return { ok: false, error: "Only CEO/Owner/Admin can create users." };
  }

  const mobile = normalizeMobile(input.mobile);
  if (!mobile) {
    return { ok: false, error: "Enter a valid 10-digit mobile number." };
  }

  let plainPin: string | null = null;
  let pinAutoGenerated = false;
  if (input.pin && input.confirmPin && input.pin !== input.confirmPin) {
    return { ok: false, error: "PIN and confirmation do not match." };
  }
  if (input.pin && isValidPin(input.pin)) {
    plainPin = input.pin;
  } else if (input.pin) {
    return { ok: false, error: "PIN must be 4–8 digits." };
  } else if (input.autoGeneratePin !== false) {
    plainPin = generateTemporaryPin();
    pinAutoGenerated = true;
  } else {
    return { ok: false, error: "PIN is required." };
  }

  const emailRaw = (input.email || "").trim().toLowerCase();
  const email =
    emailRaw && emailRaw.includes("@")
      ? emailRaw
      : internalEmailFromMobile(mobile);

  const admin = createServiceClient();

  const { data: mobileClash } = await admin
    .from("crm_user_login")
    .select("user_id")
    .eq("mobile_number", mobile)
    .maybeSingle();
  if (mobileClash) {
    return { ok: false, error: "This mobile number is already in use." };
  }

  const modules =
    sanitizeModules(input.allowedModules) || defaultModulesForRole(input.role);

  const password =
    input.temporaryPassword ||
    `Tmp!${Math.random().toString(36).slice(2)}${Date.now().toString(36)}A1`;

  const { data, error } = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: {
      app: "crm",
      crm: "true",
      role: input.role,
      full_name: input.fullName.trim(),
      mobile,
    },
  });
  if (error || !data.user) {
    return { ok: false, error: error?.message || "Failed to create auth user." };
  }

  const userId = data.user.id;
  const isActive = input.isActive !== false;

  const { error: profileErr } = await admin.from("crm_profiles").upsert({
    id: userId,
    email,
    full_name: input.fullName.trim(),
    mobile,
    role: input.role,
    is_active: isActive,
    company_scope: input.companyScope || "KALYANI",
    department: (input.department || "").trim() || null,
    allowed_modules: modules,
    is_primary_owner: false,
    is_developer: false,
  });
  if (profileErr) {
    await admin.auth.admin.deleteUser(userId);
    return { ok: false, error: profileErr.message };
  }

  const pin_hash = await hashPin(plainPin);
  const { error: loginErr } = await admin.from("crm_user_login").upsert({
    user_id: userId,
    mobile_number: mobile,
    pin_hash,
    pin_updated_at: new Date().toISOString(),
    failed_attempts: 0,
    locked_until: null,
    // CEO-set / provisioned PIN works immediately. Only developer bootstrap
    // forces must_change_pin via dedicated scripts.
    must_change_pin: false,
  });
  if (loginErr) {
    await admin.auth.admin.deleteUser(userId);
    await auditAdmin(
      input.actor.id,
      "USER_CREATED_PARTIAL",
      userId,
      { reason: loginErr.message },
      false
    );
    return { ok: false, error: loginErr.message };
  }

  const { data: companies } = await admin.from("crm_companies").select("id, code");
  const scope = input.companyScope || "KALYANI";
  for (const c of companies || []) {
    if (scope === "ALL" || scope === c.code || input.role === "OWNER") {
      await admin.from("crm_user_company_access").upsert(
        {
          user_id: userId,
          company_id: c.id,
          role: input.role,
          is_active: true,
        },
        { onConflict: "user_id,company_id" }
      );
    }
  }

  await auditAdmin(input.actor.id, "USER_CREATED", userId, {
    role: input.role,
    mobile_suffix: mobile.slice(-4),
    has_pin: true,
    pin_auto_generated: pinAutoGenerated,
    department: input.department || null,
    modules,
  });
  await writeDeveloperAudit({
    actorId: input.actor.id,
    action: "ADD_USER",
    targetUserId: userId,
    operation: "ADD_USER",
    success: true,
    metadata: { role: input.role, pin_auto_generated: pinAutoGenerated },
  });

  return {
    ok: true,
    userId,
    mobile,
    ...(pinAutoGenerated
      ? { temporaryPin: plainPin, pinAutoGenerated }
      : {}),
  };
}

export async function changeUserRole(input: {
  actor: DeveloperProfile;
  userId: string;
  newRole: AppRole;
  overrideVerified: boolean;
}): Promise<{ ok: true } | { ok: false; error: string }> {
  const target = await loadDeveloperProfile(input.userId);
  if (!target) return { ok: false, error: "User not found." };

  const protect = assertCanModifyPrimaryOwner({
    actor: input.actor,
    target,
    operation: "CHANGE_ROLE",
    overrideVerified: input.overrideVerified,
  });
  if (!protect.ok) return protect;

  if (target.is_primary_owner && input.newRole !== "OWNER") {
    return {
      ok: false,
      error: "Primary Owner cannot be demoted through normal UI.",
    };
  }

  if (input.newRole === "OWNER" && !input.overrideVerified) {
    return {
      ok: false,
      error: "Promoting to Owner requires Developer Override confirmation.",
    };
  }

  const admin = createServiceClient();
  const { error } = await admin
    .from("crm_profiles")
    .update({ role: input.newRole })
    .eq("id", input.userId);
  if (error) return { ok: false, error: error.message };

  await auditAdmin(input.actor.id, "USER_ROLE_CHANGED", input.userId, {
    previous_role: target.role,
    new_role: input.newRole,
  });
  return { ok: true };
}

export async function setUserActiveState(input: {
  actor: DeveloperProfile | Profile;
  userId: string;
  isActive: boolean;
  overrideVerified?: boolean;
}): Promise<{ ok: true } | { ok: false; error: string }> {
  const target = await loadDeveloperProfile(input.userId);
  if (!target) return { ok: false, error: "User not found." };

  if (target.is_primary_owner && !input.isActive) {
    return {
      ok: false,
      error: "Primary Owner cannot be deactivated through the normal UI.",
    };
  }

  const admin = createServiceClient();
  const patch: Record<string, unknown> = {
    is_active: input.isActive,
    deactivated_at: input.isActive ? null : new Date().toISOString(),
    deactivated_by: input.isActive ? null : input.actor.id,
  };
  const { error } = await admin
    .from("crm_profiles")
    .update(patch)
    .eq("id", input.userId);
  if (error) return { ok: false, error: error.message };

  if (!input.isActive) {
    await revokeAllDevicesAndSessions(
      input.userId,
      input.actor.id,
      "USER_DISABLED"
    );
  }

  await auditAdmin(
    input.actor.id,
    input.isActive ? "USER_ENABLED" : "USER_DISABLED",
    input.userId,
    {}
  );
  return { ok: true };
}

/** Soft-delete: deactivate + revoke. Hard delete of auth user only with override and never for primary owner. */
export async function deleteUserAccount(input: {
  actor: DeveloperProfile;
  userId: string;
  hardDelete: boolean;
  overrideVerified: boolean;
}): Promise<{ ok: true } | { ok: false; error: string }> {
  const target = await loadDeveloperProfile(input.userId);
  if (!target) return { ok: false, error: "User not found." };

  if (target.is_primary_owner) {
    return {
      ok: false,
      error: "Primary Owner cannot be deleted. Use Owner recovery procedure.",
    };
  }
  if (target.id === input.actor.id) {
    return { ok: false, error: "You cannot delete your own account." };
  }
  if (!input.overrideVerified) {
    return {
      ok: false,
      error: "Developer Override confirmation is required to delete a user.",
    };
  }

  await setUserActiveState({
    actor: input.actor,
    userId: input.userId,
    isActive: false,
    overrideVerified: true,
  });

  const admin = createServiceClient();
  if (input.hardDelete) {
    await admin.from("crm_user_login").delete().eq("user_id", input.userId);
    await admin.from("crm_auth_devices").delete().eq("user_id", input.userId);
    await admin.from("crm_user_company_access").delete().eq("user_id", input.userId);
    const { error } = await admin.auth.admin.deleteUser(input.userId);
    if (error) return { ok: false, error: error.message };
    // profile cascades from auth.users
  }

  await auditAdmin(input.actor.id, "USER_DELETED", input.userId, {
    hard_delete: input.hardDelete,
  });
  await writeDeveloperAudit({
    actorId: input.actor.id,
    action: "DELETE_USER",
    targetUserId: input.userId,
    operation: "DELETE_USER",
    success: true,
    metadata: { hard_delete: input.hardDelete },
  });
  return { ok: true };
}

export async function unlockUserAccount(input: {
  actor: DeveloperProfile | Profile;
  userId: string;
}): Promise<{ ok: true } | { ok: false; error: string }> {
  const admin = createServiceClient();
  const { error } = await admin
    .from("crm_user_login")
    .update({
      failed_attempts: 0,
      locked_until: null,
    })
    .eq("user_id", input.userId);
  if (error) return { ok: false, error: error.message };

  await auditAdmin(input.actor.id, "USER_UNLOCKED", input.userId, {});
  await writeDeveloperAudit({
    actorId: input.actor.id,
    action: "OVERRIDE_LOCKED_USER",
    targetUserId: input.userId,
    operation: "OVERRIDE_LOCKED_USER",
    success: true,
  });
  return { ok: true };
}

export async function ownerResetUserPin(input: {
  actor: DeveloperProfile | Profile;
  userId: string;
  newPin?: string;
  /** When true, generate a temporary PIN and return it once. */
  autoGenerate?: boolean;
  mobile?: string;
  operation?: DeveloperOperation;
}): Promise<
  | { ok: true; temporaryPin?: string; pinAutoGenerated?: boolean }
  | { ok: false; error: string }
> {
  let plainPin = (input.newPin || "").trim();
  let pinAutoGenerated = false;
  if (input.autoGenerate || !plainPin) {
    if (!input.autoGenerate && !plainPin) {
      return { ok: false, error: "PIN must be 4–8 digits." };
    }
    plainPin = generateTemporaryPin();
    pinAutoGenerated = true;
  } else if (!isValidPin(plainPin)) {
    return { ok: false, error: "PIN must be 4–8 digits." };
  }

  const target = await loadDeveloperProfile(input.userId);
  if (!target) return { ok: false, error: "User not found." };

  const actorIsDeveloper = Boolean(
    "is_developer" in input.actor &&
      input.actor.is_developer &&
      input.actor.role === "OWNER"
  );
  if (
    !canResetOtherUserPin(input.actor.role, target.role, { actorIsDeveloper })
  ) {
    return {
      ok: false,
      error: "You are not authorised to reset this user's PIN.",
    };
  }

  const admin = createServiceClient();
  const { data: existing } = await admin
    .from("crm_user_login")
    .select("user_id, mobile_number")
    .eq("user_id", input.userId)
    .maybeSingle();

  const mobile =
    normalizeMobile(input.mobile || "") ||
    existing?.mobile_number ||
    normalizeMobile(target.mobile || "") ||
    null;
  if (!mobile) {
    return {
      ok: false,
      error: "Set a mobile number for this user before assigning a PIN.",
    };
  }

  const { data: clash } = await admin
    .from("crm_user_login")
    .select("user_id")
    .eq("mobile_number", mobile)
    .neq("user_id", input.userId)
    .maybeSingle();
  if (clash) return { ok: false, error: "This mobile number is already in use." };

  const pin_hash = await hashPin(plainPin);
  const now = new Date().toISOString();

  if (existing) {
    const { error } = await admin
      .from("crm_user_login")
      .update({
        mobile_number: mobile,
        pin_hash,
        pin_updated_at: now,
        failed_attempts: 0,
        locked_until: null,
        // CEO-set PIN is immediately usable; users cannot self-change PIN.
        must_change_pin: false,
      })
      .eq("user_id", input.userId);
    if (error) return { ok: false, error: error.message };
  } else {
    const { error } = await admin.from("crm_user_login").insert({
      user_id: input.userId,
      mobile_number: mobile,
      pin_hash,
      pin_updated_at: now,
      must_change_pin: false,
    });
    if (error) return { ok: false, error: error.message };
  }

  await admin.from("crm_profiles").update({ mobile }).eq("id", input.userId);

  // Close any pending forgot-PIN tickets for this mobile/user
  await admin
    .from("crm_pin_reset_requests")
    .update({
      status: "FULFILLED",
      fulfilled_by: input.actor.id,
      fulfilled_at: now,
    })
    .eq("status", "PENDING")
    .or(`user_id.eq.${input.userId},mobile_number.eq.${mobile}`);

  // Invalidate remembered devices + global Supabase sessions
  await revokeAllDevicesAndSessions(
    input.userId,
    input.actor.id,
    "OWNER_PIN_RESET"
  );

  await auditAdmin(input.actor.id, "OWNER_PIN_RESET", input.userId, {
    pin_updated_at: now,
    pin_auto_generated: pinAutoGenerated,
  });
  await writeDeveloperAudit({
    actorId: input.actor.id,
    action: input.operation || "RESET_PIN",
    targetUserId: input.userId,
    operation: input.operation || "RESET_PIN",
    success: true,
    metadata: { pin_updated_at: now, pin_auto_generated: pinAutoGenerated },
  });

  return {
    ok: true,
    ...(pinAutoGenerated
      ? { temporaryPin: plainPin, pinAutoGenerated: true }
      : {}),
  };
}

export async function listAuditLogs(opts: {
  limit?: number;
  module?: string;
}) {
  const admin = createServiceClient();
  let q = admin
    .from("crm_audit_logs")
    .select(
      "id, company_id, user_id, action, module, record_type, record_id, metadata, ip_address, user_agent, created_at"
    )
    .order("created_at", { ascending: false })
    .limit(opts.limit || 100);
  if (opts.module) q = q.eq("module", opts.module);
  const { data, error } = await q;
  if (error) throw new Error(error.message);
  return data || [];
}

export async function getSecuritySettings() {
  const admin = createServiceClient();
  const { data } = await admin
    .from("crm_app_settings")
    .select("key, value, updated_at")
    .is("company_id", null)
    .in("key", ["security_role_permissions", "security_lockout_policy"]);
  const map: Record<string, string> = {};
  for (const row of data || []) map[row.key] = row.value;
  return {
    rolePermissions: safeJson(map.security_role_permissions, {}),
    lockoutPolicy: safeJson(map.security_lockout_policy, {
      max_failed_attempts: 5,
      lockout_minutes: 15,
    }),
  };
}

async function upsertGlobalSetting(
  key: string,
  value: string,
  updatedBy: string
) {
  const admin = createServiceClient();
  const { data: existing } = await admin
    .from("crm_app_settings")
    .select("id")
    .is("company_id", null)
    .eq("key", key)
    .maybeSingle();
  if (existing?.id) {
    await admin
      .from("crm_app_settings")
      .update({ value, updated_by: updatedBy })
      .eq("id", existing.id);
  } else {
    await admin.from("crm_app_settings").insert({
      company_id: null,
      key,
      value,
      is_public: false,
      updated_by: updatedBy,
    });
  }
}

export async function updateSecuritySettings(input: {
  actor: DeveloperProfile;
  rolePermissions?: unknown;
  lockoutPolicy?: unknown;
}) {
  if (input.rolePermissions !== undefined) {
    await upsertGlobalSetting(
      "security_role_permissions",
      JSON.stringify(input.rolePermissions),
      input.actor.id
    );
  }
  if (input.lockoutPolicy !== undefined) {
    await upsertGlobalSetting(
      "security_lockout_policy",
      JSON.stringify(input.lockoutPolicy),
      input.actor.id
    );
  }
  await auditAdmin(input.actor.id, "SECURITY_SETTINGS_CHANGED", null, {
    updated_role_permissions: input.rolePermissions !== undefined,
    updated_lockout: input.lockoutPolicy !== undefined,
  });
}

function safeJson<T>(raw: string | undefined, fallback: T): T {
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export { MANAGEABLE_ROLES };
