"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { ROLE_PERMISSIONS, type AppRole } from "@/types/database";
import {
  CRM_MODULES,
  DEFAULT_MODULES_BY_ROLE,
  MODULE_LABELS,
  type CrmModule,
} from "@/lib/auth/modules";

const ROLES: AppRole[] = [
  "OWNER",
  "CEO_1",
  "CEO_2",
  "CEO_3",
  "ADMIN",
  "SALES_MANAGER",
  "SALESMAN",
  "ACCOUNTANT",
  "VIEWER",
];

const DEPARTMENTS = [
  "Management",
  "Sales",
  "Accounts",
  "Operations",
  "Support",
  "Other",
];

export function AddUserForm({
  actorIsDeveloper,
}: {
  actorIsDeveloper: boolean;
  overrideConfigured?: boolean;
}) {
  const router = useRouter();
  const [fullName, setFullName] = useState("");
  const [role, setRole] = useState<AppRole>("SALESMAN");
  const [mobile, setMobile] = useState("");
  const [pin, setPin] = useState("");
  const [confirmPin, setConfirmPin] = useState("");
  const [department, setDepartment] = useState("Sales");
  const [companyScope, setCompanyScope] = useState("KALYANI");
  const [isActive, setIsActive] = useState(true);
  const [modules, setModules] = useState<CrmModule[]>(
    DEFAULT_MODULES_BY_ROLE.SALESMAN
  );
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [generatedPin, setGeneratedPin] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  const roleOptions = useMemo(
    () =>
      ROLES.filter((r) => {
        if (r === "OWNER") return true;
        return true;
      }),
    []
  );

  function onRoleChange(next: AppRole) {
    setRole(next);
    setModules(DEFAULT_MODULES_BY_ROLE[next] || ["dashboard"]);
    if (next === "ACCOUNTANT") setDepartment("Accounts");
    else if (next === "SALESMAN" || next === "SALES_MANAGER")
      setDepartment("Sales");
    else if (next === "OWNER" || next.startsWith("CEO"))
      setDepartment("Management");
  }

  function toggleModule(mod: CrmModule) {
    setModules((prev) =>
      prev.includes(mod) ? prev.filter((m) => m !== mod) : [...prev, mod]
    );
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setPending(true);
    setError(null);
    setMessage(null);
    setGeneratedPin(null);
    try {
      if (pin && pin !== confirmPin) {
        throw new Error("PIN and confirmation do not match.");
      }
      if (!window.confirm(`Create user ${fullName} as ${ROLE_PERMISSIONS[role]?.label || role}?`)) {
        setPending(false);
        return;
      }
      const res = await fetch("/api/admin/users", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fullName,
          role,
          mobile,
          pin: pin || undefined,
          confirmPin: confirmPin || undefined,
          companyScope,
          department,
          allowedModules: modules,
          isActive,
          confirm: true,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || "Failed to create user");
      if (data.temporaryPin) {
        setGeneratedPin(String(data.temporaryPin));
        setMessage(
          data.pinAutoGenerated
            ? "User created. Temporary PIN was auto-generated — copy it now; it will not be shown again."
            : "User created. Share the temporary PIN below."
        );
      } else {
        setMessage(
          "User created. They can log in immediately with the mobile number and PIN."
        );
      }
      setFullName("");
      setMobile("");
      setPin("");
      setConfirmPin("");
      router.refresh();
      if (data.userId && !data.temporaryPin) {
        router.push(`/settings/users/${data.userId}/security`);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed");
    } finally {
      setPending(false);
    }
  }

  return (
    <form
      onSubmit={onSubmit}
      className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5 space-y-3 max-w-2xl"
    >
      <h3 className="font-semibold">Add user</h3>
      <p className="text-xs text-[var(--muted)]">
        Creates a real database login. Users sign in with Mobile Number + PIN
        only — no email/password on the login screen.
        {actorIsDeveloper
          ? " Developer identity stays hidden from normal CEO lists."
          : ""}
      </p>
      <input
        required
        type="text"
        placeholder="Full name"
        value={fullName}
        onChange={(e) => setFullName(e.target.value)}
        className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm"
      />
      <input
        required
        type="tel"
        inputMode="numeric"
        placeholder="10-digit mobile number"
        value={mobile}
        onChange={(e) => setMobile(e.target.value)}
        className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm"
      />
      <div className="grid gap-3 sm:grid-cols-2">
        <select
          value={role}
          onChange={(e) => onRoleChange(e.target.value as AppRole)}
          className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm"
        >
          {roleOptions.map((r) => (
            <option key={r} value={r}>
              {ROLE_PERMISSIONS[r]?.label || r}
            </option>
          ))}
        </select>
        <select
          value={department}
          onChange={(e) => setDepartment(e.target.value)}
          className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm"
        >
          {DEPARTMENTS.map((d) => (
            <option key={d} value={d}>
              {d}
            </option>
          ))}
        </select>
      </div>
      <select
        value={companyScope}
        onChange={(e) => setCompanyScope(e.target.value)}
        className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm"
      >
        <option value="KALYANI">Kalyani</option>
        <option value="RADHASWAMI">Radhaswami</option>
        <option value="ALL">All companies</option>
      </select>
      <div className="grid gap-3 sm:grid-cols-2">
        <input
          type="password"
          inputMode="numeric"
          maxLength={8}
          placeholder="PIN (4–8 digits)"
          value={pin}
          onChange={(e) => setPin(e.target.value.replace(/\D/g, "").slice(0, 8))}
          className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm tracking-[0.25em]"
        />
        <input
          type="password"
          inputMode="numeric"
          maxLength={8}
          placeholder="Confirm PIN"
          value={confirmPin}
          onChange={(e) =>
            setConfirmPin(e.target.value.replace(/\D/g, "").slice(0, 8))
          }
          className="w-full rounded-md border border-[var(--border)] px-3 py-2 text-sm tracking-[0.25em]"
        />
      </div>
      <p className="text-xs text-[var(--muted)]">
        Leave PIN blank to auto-generate a temporary 6-digit PIN (shown once).
      </p>
      <label className="flex items-center gap-2 text-sm">
        <input
          type="checkbox"
          checked={isActive}
          onChange={(e) => setIsActive(e.target.checked)}
          className="h-4 w-4 accent-[var(--accent)]"
        />
        Active
      </label>
      <fieldset className="rounded-md border border-[var(--border)] p-3">
        <legend className="px-1 text-sm font-medium">Allowed modules</legend>
        <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">
          {CRM_MODULES.map((mod) => (
            <label key={mod} className="flex items-center gap-2 text-xs">
              <input
                type="checkbox"
                checked={modules.includes(mod)}
                onChange={() => toggleModule(mod)}
              />
              {MODULE_LABELS[mod]}
            </label>
          ))}
        </div>
      </fieldset>
      {error && (
        <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-800">
          {error}
        </p>
      )}
      {message && (
        <p className="rounded-md bg-emerald-50 px-3 py-2 text-sm text-emerald-800">
          {message}
        </p>
      )}
      {generatedPin && (
        <div className="rounded-md border border-amber-300 bg-amber-50 px-3 py-3 text-sm text-amber-950">
          <p className="font-semibold">Temporary PIN (copy now)</p>
          <p className="mt-1 font-mono text-2xl tracking-[0.35em]">
            {generatedPin}
          </p>
        </div>
      )}
      <button
        type="submit"
        disabled={pending || !fullName || !mobile}
        className="rounded-md bg-[var(--accent)] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60"
      >
        {pending ? "Saving…" : "SAVE USER"}
      </button>
    </form>
  );
}
