#!/usr/bin/env node
/**
 * Bootstrap CRM owner user (server-side only).
 * Usage:
 *   OWNER_EMAIL=... OWNER_PASSWORD=... OWNER_NAME="..." node scripts/seed-owner.js
 */
const { createClient } = require("@supabase/supabase-js");

const url =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  "https://pelwnhukierrqienpveb.supabase.co";
const serviceKey =
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY;

async function main() {
  const email = process.env.OWNER_EMAIL || process.env.CRM_OWNER_EMAIL;
  const password = process.env.OWNER_PASSWORD || process.env.CRM_OWNER_PASSWORD;
  const fullName =
    process.env.OWNER_NAME || process.env.CRM_OWNER_NAME || "System Administration";
  const mobileRaw = process.env.OWNER_MOBILE || process.env.CRM_OWNER_MOBILE || "";
  let ownerPin =
    process.env.OWNER_LOGIN_PIN ||
    process.env.CRM_OWNER_LOGIN_PIN ||
    process.env.DEVELOPER_LOGIN_PIN ||
    process.env.CRM_DEVELOPER_LOGIN_PIN ||
    "";
  const mobile = mobileRaw.replace(/\D/g, "").slice(-10);
  let pinAutoGenerated = false;
  let pinFromEnvBootstrap = Boolean(
    process.env.OWNER_LOGIN_PIN ||
      process.env.CRM_OWNER_LOGIN_PIN ||
      process.env.DEVELOPER_LOGIN_PIN ||
      process.env.CRM_DEVELOPER_LOGIN_PIN
  );

  if (!serviceKey) throw new Error("SUPABASE_SERVICE_ROLE_KEY required");
  if (!email || !password) {
    throw new Error("OWNER_EMAIL and OWNER_PASSWORD required");
  }

  // Auto-generate a temporary mobile PIN when mobile is set but PIN is omitted.
  if (mobile.length === 10 && !/^[0-9]{4,8}$/.test(ownerPin)) {
    const { randomInt } = require("crypto");
    ownerPin = Array.from({ length: 6 }, () => String(randomInt(0, 10))).join("");
    pinAutoGenerated = true;
  }

  const admin = createClient(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const { data: listed } = await admin.auth.admin.listUsers({ perPage: 200 });
  let user = listed?.users?.find((u) => u.email === email);

  if (!user) {
    const { data, error } = await admin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: {
        app: "crm",
        crm: "true",
        role: "OWNER",
        full_name: fullName,
      },
    });
    if (error) throw error;
    user = data.user;
    console.log("Created auth user", user.id);
  } else {
    console.log("Auth user exists", user.id);
    await admin.auth.admin.updateUserById(user.id, {
      password,
      user_metadata: {
        ...(user.user_metadata || {}),
        app: "crm",
        crm: "true",
        role: "OWNER",
        full_name: fullName,
      },
    });
  }

  const { error: upsertError } = await admin.from("crm_profiles").upsert({
    id: user.id,
    email,
    full_name: fullName,
    mobile: mobile.length === 10 ? mobile : null,
    role: "OWNER",
    is_active: true,
    company_scope: "ALL",
    is_primary_owner: true,
    is_developer: true,
  });
  if (upsertError) throw upsertError;

  if (mobile.length === 10 && ownerPin && /^[0-9]{4,8}$/.test(ownerPin)) {
    const bcrypt = require("bcryptjs");
    const pin_hash = await bcrypt.hash(ownerPin, 12);
    const { error: loginErr } = await admin.from("crm_user_login").upsert({
      user_id: user.id,
      mobile_number: mobile,
      pin_hash,
      pin_updated_at: new Date().toISOString(),
      failed_attempts: 0,
      locked_until: null,
      // Force change after env bootstrap / auto-generated temporary PIN
      must_change_pin: pinAutoGenerated || pinFromEnvBootstrap,
    });
    if (loginErr) throw loginErr;
    console.log("Owner mobile+PIN login ready for", mobile);
    if (pinAutoGenerated) {
      console.log("AUTO_GENERATED_OWNER_LOGIN_PIN=" + ownerPin);
      console.log(
        "Copy the temporary PIN above now — it is not stored in plaintext."
      );
    } else if (pinFromEnvBootstrap) {
      console.log(
        "Bootstrap PIN applied from env. User must change PIN after first login (must_change_pin=true)."
      );
    }
  } else if (mobile.length === 10 || ownerPin) {
    console.log(
      "Skip mobile+PIN (need OWNER_MOBILE 10 digits and OWNER_LOGIN_PIN / DEVELOPER_LOGIN_PIN 4–8 digits)"
    );
  }

  const { data: companies, error: cErr } = await admin
    .from("crm_companies")
    .select("id, code");
  if (cErr) throw cErr;

  for (const c of companies || []) {
    const { error } = await admin.from("crm_user_company_access").upsert(
      {
        user_id: user.id,
        company_id: c.id,
        role: "OWNER",
        is_active: true,
      },
      { onConflict: "user_id,company_id" }
    );
    if (error) throw error;
  }

  console.log("Owner profile ready for", email);
}

main().catch((e) => {
  console.error(e.message || e);
  process.exit(1);
});
